apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mealie
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v1.3.2
          ports:
            - containerPort: 9000

localhost:9000

        - name: mealie
          image: httpd
          ports:
            - containerPort: 8000
        - name: mealie
          image: nginx
          ports:
            - containerPort: 7000
